### ISSUE TITLE
not getting rewards

### ISSUE THREAD

**Issue by ThePro1604** [TSEcho/VoteParty#1]
people are voting when the vote party is reached nothing happens no one gets the rewards

**Comment by ThePro1604** [comment]
up

**Comment by TSEcho** [comment]
@ThePro1604 

Will need your VoteParty version, NuVotifier version, and a copy of your config. The latest is the current stable version and is running bug free on many servers including my own

**Comment by ThePro1604** [comment]
NuVotifier version: 2.3.5
VoteParty version: 1.3.4

my config:
Commands=[
    "hc key dropparty %player%",
    "adminpay %player% 1 coin"
]
Global-Commands=[
    "broadcast &a&lVoteParty has been reached!"
]
Mechanics {
    Counter=1
    Required-Votes=100
}
Messages {
    Broadcast="&b&lVoteParty has been reached!"
    Message="&a&oYou have been given 1 Vote Coin, and a Drop Party Crate!"
    Scoreboard-Title="&a&lVoteParty"
}
Settings {
    Offline-Commands=false
    # Options: "Vote", " Timer", "Command", "Never"
    Scoreboard-Mode=false
    Send-Broadcast=true
    Send-Commands=true
    Send-Global-Commands=true
    Send-Messages=true
}

**Comment by TSEcho** [comment]
Can you attempt to fakevote or change the counter and see if you can manually trigger the event? Your current settings will only send commands for the online players at the time not anyone offline.

Additionally, are you running NuVotifier or something like SeriousNuVotifier? Only the prior will work with this plugin so you must use it. Either way it seems you’re running on an outdated version
